### ISSUE TITLE
Notifications not leading to article

### ISSUE THREAD

**Issue by Baskjgf** [spacecowboy/Feeder#654]
### Checklist

- [x] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [x] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [x] I will describe the problem with as much detail as possible.
- [x] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.9.2

### Where did you get the app from

Google Play

### Are you using the "Parse full article" feature?

Yes

### Android version

12

### Device model

Samsung Galaxy S10+

### First occurred

2-3 days ago

### Steps to reproduce

Click on any of the Feeder notifications 

### Expected behaviour

After clicking one of the notifications with a title from an article, the article should open in the app. 

### Current behaviour

After clicking one of the notifications Feeder opens, but does not lead to the article clicked. Instead it opens Feeder to the last feed it was closed at.

**Comment by spacecowboy** [comment]
I have noted this some times too. It's not consistent though.

**Comment by Baskjgf** [comment]
Any idea what can be done? Unistalling and reinstalling didn't help and neither clearing the data and cache :/

**Comment by ubeydsahin** [comment]
I get the same error, the notification comes, I press it and it does not switch to the relevant field. It does not switch to the article that comes with the notification.

**Comment by luewolf** [comment]
This started happening to me right after installing the 2.9.2 update.

**Comment by spacecowboy** [comment]
> This started happening to me right after installing the 2.9.2 update. It was working correctly in 2.9.1.

No it didn't.  It has been an issue for years.

But as I said. It's not consistent. It depends on what state the app is in, if it's open in the background or not, etc.

**Comment by jpmanuell** [comment]
Same issue here on S24 Ultra. It was working fine before.. this issue keeps happening most of the time now. And it is then difficult to navigate to the article for which the notification was clicked on since the notification is cleared once we click it. It has become an annoying issue lately.

**Comment by sivaraam** [comment]
+1 facing the same notification issue and it started happening to me only recently. I'm using v2.10.0 of the app on an Android 12 device.

**Comment by EmeDuEnT** [comment]
I've also had this issue since the last update: 2.9.2

Using a Samsung s23 ultra. All current os security patches.

**Comment by luewolf** [comment]
After installing 2.10.1, it's now working again for me

**Comment by jpmanuell** [comment]
Same.. this issue is resolved now with the update.

**Comment by spacecowboy** [comment]
I'd just like to point out that the relevant code did not change in any of the versions you are reporting.

So I'm pretty sure the problem is still there. It's just that it is not consistent.

**Comment by jpmanuell** [comment]
I stand corrected. This issue is still present. Its very inconsistent. However, until the latest update clicking on the notifications was not working properly almost every single time. After this update though this was working as intended for most of the time for me. And now its back to square one. The bug is showing up again.

**Comment by spacecowboy** [comment]
> I stand corrected. This issue is still present. Its very inconsistent. However, until the latest update clicking on the notifications was not working properly almost every single time. After this update though this was working as intended for most of the time for me. And now its back to square one. The bug is showing up again.

Have you disabled battery optimization for the app? I have long suspected that it's related to if the system puts the app into standby in the background or not

**Comment by jpmanuell** [comment]
I have now disabled battery optimization. Will update later if there is
change in app behavior.
